package main.messageStructure;

import org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory;

import javax.jms.*;
import javax.naming.InitialContext;

public class RequestReplyDemo {
    /*
    We will learn
    JMSReplyTo - property in which producer send reply to queue,
     which could be
     temporary queue-  Temporary Queue
     or JNDI  configured Queue.
     We will also check
     messageId - Id generated by Active MQ producer and
     correlationID - Id defining the relation between producer request and consumer received message
     correlationId at consumer end is same as the messageId at producer end.

     JMSReplyTo, correlationId both set at message body
     */
        public static void main(String[] args) throws Exception {
            InitialContext initialContext = new InitialContext();
            Queue requestQueue = (Queue) initialContext.lookup("queue/requestQueue");
//        Queue replyQueue = (Queue) initialContext.lookup("queue/replyQueue");

            // using try with resources all classes implementing AutoCloseable will get closed by JVM
            try (ActiveMQConnectionFactory amqCf = new ActiveMQConnectionFactory();
                 JMSContext jmsContext = amqCf.createContext()) {
                JMSProducer producer = jmsContext.createProducer();
                TemporaryQueue replyQueue = jmsContext.createTemporaryQueue();
                TextMessage message = jmsContext.createTextMessage("Arise, Awake and Stop not till the goal is reached");
                // setting reply queue in which consumer reply with its message on receiving the message from producer
                message.setJMSReplyTo(replyQueue);
                producer.send(requestQueue, message);

                System.out.println(message.getJMSMessageID());

                // receiving the producer's sent message
                JMSConsumer consumer = jmsContext.createConsumer(requestQueue);
                TextMessage messageReceived = (TextMessage) consumer.receive();
                System.out.println(messageReceived.getText());
                //now after receiving the message from the producer we have sent message to replyQueue
                // in this case consumer has to be producer and set the correlationId

                JMSProducer replyProducer = jmsContext.createProducer();
                TextMessage replyMessage = jmsContext.createTextMessage("Thanks for the quote");

                replyMessage.setJMSCorrelationID(messageReceived.getJMSMessageID());
                replyProducer.send(messageReceived.getJMSReplyTo(), replyMessage);

                //consumer of replyTo Queue
                JMSConsumer replyConsumer = jmsContext.createConsumer(replyQueue);
                TextMessage replyReceived = (TextMessage) replyConsumer.receive();
//            System.out.println("Reply from Consumer: "+replyReceived.getText());
                System.out.println(replyReceived.getJMSCorrelationID());



            }
        }
    }